name: Daily Task to Update Appointments, [date] and time

on:
  schedule:
    - cron: '1 22 * * *'  # Run every day at 12:01 Israel time (Winter, UTC+2)
  workflow_dispatch:  # Manual run by button

jobs:
  update-appointments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print current Israel time
        run: |
          node -e "
          const now = new Date().toLocaleString('en-US', { timeZone: 'Asia/Jerusalem' });
          console.log('Current Israel Time:', now);
          "

      - name: Run update appointments task
        run: |
          curl -X POST https://my-tor.vercel.app/api/generate-schedule